---
- name: Install nginx
  hosts: localhost
  become: true

  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present

  - name: Insert Index Page
    template:
      src: index.html
      dest: /var/www/html/index.nginx-debian.html 

  - name: Start NGiNX
    service:
      name: nginx
      state: started
